version: "3.9"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_EXTERNAL_PORT:-8000}:${APP_PORT:-8000}"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local