version: "3.9"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local